typography_spectrum: 0.7724987398833036
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.1489736377261579
  lightness: 0.1697228718549013
  saturation: 0.8807705768849701
  rhythmicContrast: 0.2905186964198947
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.46543731284327805
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Marissa Brassfield
  email: marissa@ridiculouslyefficient.com
  url: 'http://ridiculouslyefficient.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2274aa0d-1d48-402c-aaa2-6412c35a3277.png
name: Ridiculously Efficient
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/61cdc58c-3013-4de2-b8f0-aa63ef89ba06.ico
title: Unshackle Your Schedule
description: Creating Freedom Through High Performance
purpose: []
